# Generated by Django 5.1.1 on 2024-09-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('capa', models.ImageField(upload_to='lib_shop/images/')),
                ('descricao', models.CharField(max_length=2000)),
                ('pdf', models.FileField(upload_to='lib_shop/pdf/')),
                ('quantidade_paginas', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorias', models.ManyToManyField(related_name='livros', to='lib_shop.categoria')),
            ],
        ),
    ]
