# Generated by Django 5.1.1 on 2024-09-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(upload_to='lib_shop/capas/'),
        ),
    ]
