# Generated by Django 5.1.1 on 2024-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_shop', '0005_saldo_usuario_biblioteca_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo_usuario',
            name='livro_coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
